[package]
name = "turn-game"
version = "0.1.0"
authors = ["Mani Kamali <kamalisarvestani.1@themetroschool.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
